### ISSUE TITLE
Can't run Android Appium tests  "this.shell(...).trim is not a function"

### ISSUE THREAD

**Issue by lallish** [appium/appium#7114]
## The problem

Since I upgraded appium from 1.4.9 to 1.6.0 I'm not able to run my python appium tests anymore.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.9
* Desktop OS/version used to run Appium: OS X El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): 5.7.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device, Sony Xperia Z3
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/lallish/3c210e8c41eaa3fb43b0845f9e798bbe

## Code To Reproduce Issue [ Good To Have ]

This is my desired capabilities:

        self.desired_caps['platformName'] = 'Android'
        self.desired_caps['platformVersion'] = '6.0.1'
        self.desired_caps['deviceName'] = 'Android'
        self.desired_caps['automationName'] = "Appium"
        self.desired_caps['app'] = self.app_file
        self.desired_caps['app-package'] = 'com.axis.acc'
        self.desired_caps['appActivity'] = self.START_ACTIVITY
        self.desired_caps['appWaitActivity'] = '%s,%s,%s' % \
           (OAuthView.ACTIVITY, self.START_ACTIVITY, SitesView.ACTIVITY)
        self.desired_caps['newCommandTimeout'] = '6000'

I've tried with other platform versions but they seem to give the same result. Appium manages to start the app but then 1 sec after appium kills the app.

**Comment by JaniJegoroff** [comment]
See https://github.com/appium/appium/issues/6978

**Comment by lallish** [comment]
I tried with the shrink-wrap "npm install -g appium --no-shrinkwrap" but get the same error

**Comment by jlipps** [comment]
@lallish did you `npm uninstall -g appium` first? try that first. if that doesn't work, what is on line `427` of the file located at the output of this command?

```
ls $(npm -g prefix)/lib/node_modules/appium/node_modules/appium-adb/lib/tools/adb-commands.js
```

**Comment by jlipps** [comment]
it should look like this:

```
let stdout = (await this.shell(["ps"])).trim();
```

and not this:

```
let stdout = await this.shell(["ps"]).trim();
```

And that's how you'll know you've got the right version of appium-adb

**Comment by lallish** [comment]
Alright, it worked now! A follow-up problem I had with updating appium to 1.6.0 was that my find_elements_by_name functions was deprecated, but using find_elements_by_accessibility_id instead solved that.

**Comment by jlipps** [comment]
Yes, we got rid of finding elements by name in appium 1.5. Glad it works now!
