### ISSUE TITLE
npm install -g appium fails for 1.6.1, 1.6.2, 1.6.3 

### ISSUE THREAD

**Issue by skhanam** [appium/appium#8496]
I am on latest version of npm & on node

When i upgrade from 1.4.x to 1.6.x 

I see the below error 

I followed what was mentioned as a  first step to upgrade.
npm uninstall -g appium

I see this error : Is this npm issue ??
npm uninstall -g appium
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "uninstall" "-g" "appium"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/<username>/.npm/_logs/2017-05-20T17_08_53_570Z-debug.log

**Comment by mykola-mokhnach** [comment]
It's an npm issue and it has nothing to do with Appium. Please read https://github.com/nodejs/node/issues/9377 for more details.
