### ISSUE TITLE
IOSDriver not launching after updating appium java client to 1.6.0

### ISSUE THREAD

**Issue by ChrisG199** [appium/appium#10915]
I just updated my appium java client from 5.0.4 to 6.0.0 and now get the following error when I try to launch my test:

java.lang.NoSuchMethodError: org.openqa.selenium.remote.http.HttpClient$Factory.createDefault()Lorg/openqa/selenium/remote/http/HttpClient$Factory;

	at io.appium.java_client.remote.AppiumCommandExecutor.<init>(AppiumCommandExecutor.java:92)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)
	at Config.DriverFactory.getiOSDriver(DriverFactory.java:79)
	at iOSTests.CheckoutTestiOS.setupSuite(CheckoutTestiOS.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

It works as soon as I change it back to 5.0.4, the method I'm using to return the IOSDriver looks as follows:

   public IOSDriver getiOSDriver() throws MalformedURLException, IOException {

        // Start the appium server
        AppiumDriverLocalService service = AppiumDriverLocalService.buildDefaultService();
        service.start();

        DesiredCapabilities capabilities = new DesiredCapabilities();

        // Set the capability to execute test in iOS app
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("deviceName", "iPhone 8");
        capabilities.setCapability("platformVersion", "11.4");
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("app", System.getProperty("user.dir")+"/MyApp/iOS/MyApp.app");

        return new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
    }

**Comment by vjmaiky** [comment]
install latest appium beta and give it a try

**Comment by ChrisG199** [comment]
I upgraded to latest appium beta, but it's still giving me the same error

**Comment by mykola-mokhnach** [comment]
The issue has nothing to do with appium server and this is a java dependency issue on the client side.
