### ISSUE TITLE
Couldn't find any element on "share" iOS13 system screen and appium 1.15.0

### ISSUE THREAD

**Issue by insidiaGithub** [appium/appium#13403]
## The problem

Hi! I have a test that opens image -> tap on share button -> then it should tap on "Save Image". It works with iOS12 and appium 1.14, but after upgrade to iOS13 (it contains new 'share' system screen) I can't find any element on this screen.

Inspector in appium desktop returns me error "e.replace is not a function" when I try to get hierarchy of elements. Driver.PageSource (с#) returns me error "Could not proxy command to remote server. Original error: Error: socket hang up" (see logs below).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: MacOS Catalina
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 13.0 - 13.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/insidiaGithub/3299b4da16c0290492a2380b1c1d87de
![Снимок_экрана_101019_121620_PM](https://user-images.githubusercontent.com/42467168/66555861-fe248880-eb57-11e9-9e99-4673d2c0f825.jpg)
![Снимок_экрана_101019_121934_PM](https://user-images.githubusercontent.com/42467168/66556030-388e2580-eb58-11e9-9457-15d7c3a02fd9.jpg)

## Code To Reproduce Issue [ Good To Have ]

var test = Driver.PageSource;   - when share screen is open
var saveButton = Driver.FindElementsByAccessibilityId("Save Image");      - returns 0 items (this is a code from the working environment with iOS 12)

**Comment by mykola-mokhnach** [comment]
Try to enable the `includeNonModalElements` setting

**Comment by mykola-mokhnach** [comment]
What is the crash?

**Comment by insidiaGithub** [comment]
After I tried find any element on share screen, I've got this log:
https://gist.github.com/insidiaGithub/578bbb8c1ef2acee3e7ce46895e018fd

**Comment by insidiaGithub** [comment]
> What is the crash?

After I tried find any element on share screen, I've got this log:
https://gist.github.com/insidiaGithub/578bbb8c1ef2acee3e7ce46895e018fd

**Comment by mykola-mokhnach** [comment]
Can you enable the device logs in caps to see the stack trace?

**Comment by insidiaGithub** [comment]
> Can you enable the device logs in caps to see the stack trace?

Sure, but is very big. My log with `showIOSLog` on share screen :
https://gist.github.com/insidiaGithub/3ee47cd4363d10bfe0be2640ab096c04

**Comment by mykola-mokhnach** [comment]
To me it looks like a crash inside xctest itself. Can you please attach the diagnostic log generated by Xcodebuild (the one mentioned in the Appium log)?

**Comment by insidiaGithub** [comment]
@mykola-mokhnach thank you. If you told about this diagnostic log:
`IDETestOperationsObserverDebug: Writing diagnostic log for test session to`
here it is:
[Test-WebDriverAgentRunner-2019.10.10_20-27-03-+0000.xcresult.zip](https://github.com/appium/appium/files/3714575/Test-WebDriverAgentRunner-2019.10.10_20-27-03-%2B0000.xcresult.zip)

**Comment by mykola-mokhnach** [comment]
I would like to see the log at 

> 2019-10-10 13:09:11.953 xcodebuild[44790:7527153]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> [Xcode] /Users/acumaticamobile/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2019.10.10_13-05-40-+0000.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-233FE108-34A0-4E37-9A51-07278D0C8AA7/WebDriverAgentRunner-39A0413D-B52A-4C68-8544-48DDD282E98B/Session-WebDriverAgentRunner-2019-10-10_130911-Jmdsl1.log

**Comment by mykola-mokhnach** [comment]
There is nothing more we can do on this issue without the actual stack trace

**Comment by insidiaGithub** [comment]
> There is nothing more we can do on this issue without the actual stack trace

Thanks for you help! I've tried to install xcode 11.2 beta 2 with iOS simulator 13.2 and now I can find any element with 1.15 appium. It was problem with xcode or simulator
