### ISSUE TITLE
Could not find Android emulator after upgrade to Android studio 2.0 beta

### ISSUE THREAD

**Issue by nieschumi** [appium/appium#6392]
After we upgraded Android Studio to 2.0, android emulator get upgraded to, when we are running the same test, we get this error: A new session could not be created. (Original error: Could not find Nexus6 emulator.). 

## Environment

* Appium 1.5.1 and 1.4.16
* Desktop OS/version used to run Appium: OS X EI Capitan 10.11.3 and 10.11.1
* Node.js version (unless using Appium.app|exe): v0.12.7 and v4.2.1
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: emulator

## Link to Appium logs
Note that there's a physical Android device connected to the test machine. No emulator is open previously.
https://gist.github.com/nieschumi/ce04f52ac9926b199c98ea0742360a53

## Code To Reproduce Issue [ Good To Have ]
    public static DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability("deviceName", "Nexus6");
    capabilities.setCapability("platformVersion", "6.0");
    capabilities.setCapability("platformName", "Android");
    capabilities.setCapability("avd", "Nexus6");

Attached is a screenshot of my emulator config.
![screen shot 2016-04-11 at 2 09 33 pm](https://cloud.githubusercontent.com/assets/6202028/14439101/0fb6d8ee-ffef-11e5-8841-171b6efcafdc.png)

**Comment by scottdixon** [comment]
What's the output of `emulator -list-avds`?

**Comment by nieschumi** [comment]
The output is:

AVD_for_Nexus_4_by_Google
Nexus6
Nexus9
Nexus_5_API_23_x86

**Comment by imurchie** [comment]
The latest Android SDK update changed how the telnet daemon responded, breaking our handling of finding the running device.

It has been fixed here: https://github.com/appium/appium-adb/commit/a11d382dbad77854388ddb60fa1ac4860057f8ad

And it has been released in `appium-adb@2.6.1`. Install that, and it ought to work.

**Comment by nieschumi** [comment]
I installed appium-adb@2.6.1, the correct emulator is launched, but I'm still getting this "Could not find Nexus6 emulator". Appium log shows

[debug] [ADB] Emulator Nexus6 not running
[debug] [ADB] Trying to find Nexus6 emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] 0 emulator(s) connected
[debug] [ADB] Emulator Nexus6 not running
[debug] [ADB] Trying to find Nexus6 emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: a[K[Dav[K[D[Davd[K[D[D[Davd [K[D[D[D[Davd n[K[D[D[D[D[Davd na[K[D[D[D[D[D[Davd nam[K[D[D[D[D[D[D[Davd name[K
Nexus6
[debug] [ADB] Emulator Nexus6 not running

**Comment by nieschumi** [comment]
By the way is appium-adb something we need to install separately?

**Comment by imurchie** [comment]
You need to install it within Appium. You can install Appium with the
--no-shrinkwrap option, or go into the correct place and install
Appium-adb. You would need to look around to find the correct place for
that, depending on your system.

**Comment by nieschumi** [comment]
I don't know how to install appium-adb separately,  I guess I need to install it using npm under appium-selendroid-driver/node_modules folder right?

Apart from that, I have verified this issue is fixed. Thanks!

**Comment by IntelloScooby** [comment]
I installed appium-adb@2.6.1 by using the command `npm install appium-adb@2.6.1` on my mac. It installed the package successfully under node_modules. But still getting the same error that it is not able to find android emulator Nexus6. 
Note that we are on appium 1.4.16 and we cannot upgrade to appium 1.5 at this point

**Comment by nieschumi** [comment]
After we upgrade to 1.5.1,  AndroidDriver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS) has stopped working, the wait time is not set, I create an other issue here.

Can someone shed a light on how to install appium-adb ? For your information, this is appium-adb module path on my Mac:
/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/appium-adb

**Comment by imurchie** [comment]
You don't need to install it separately. That _will not_ work. 

Either:

1. install appium again, using `npm install -g appium --no-shrinkwrap`
1. find where `appium-adb` is within your install of appium, and install there
1. wait for appium 1.5.2 to be released.

**Comment by lvconley** [comment]
We have the same issue. The features that I need to automate require AVDs that have been created with Android Studio 2.0. But the Appium GUI app 1.4.13 can't see the AVDs once they are launched (launching the AVD from Appium works fine, though), and this prevents the Appium Inspector from being used. Installing headless Appium 1.5.2 won't do me any good, since I need the Appium Inspector to build my automation.

Thus, any idea when the Appium GUI app will be updated so that it can work with Android Studio 2+ AVDs?

Or is there a clever way of installing headless 1.5.2 and then getting the 1.4.13 GUI app to use it accordingly?

**Comment by rompic** [comment]
@ivconley i haven't tested it myself but this is described in https://saucelabs.com/resources/webinars/10-things-you-didnt-know-about-appium

![appium](https://cloud.githubusercontent.com/assets/6322123/14842711/583d6616-0c4a-11e6-9c30-00f87ccafd55.png)

**Comment by imurchie** [comment]
You will need Appium 1.5.2 in order to interact with avds created in Android Studio 2.

**Comment by lvconley** [comment]
@rompic, thanks for the tip! I went ahead and tried that after using npm to install Appium 1.5.2 with the following command:

npm install -g appium@1.5.2

Once the installation had completed, I ran the following command at the terminal to verify that I had 1.5.2 installed:

appium -v

Which returned:

1.5.2

After verifying that 1.5.2 had been correctly installed by npm, I used the "which" to verify path to node.js:

which node

This returned: /usr/local/bin/node

So, that's the path that I placed in the "external NodeJS" field in the "Developer Settings" field.

I then ran the following command from the terminal to see where appium had been installed by npm:

which appium

This returned: /usr/local/bin/nappium

And that's what I entered "External Appium Package" setting. But then when I tried to launch from the Appium GUI interface, node never launches.

I then did more searching for files with the name appium in them and found the following 

/usr/local/lib/node_modules/appium

So, I plugged that path into the "External Appium Package" field in "Developer Settings" and tried to launch and got the following error:
 
Error: Cannot find module '/usr/local/lib/node_modules/appium/lib/server/main.js'

So, I noted that the /usr/local/lib/node_modules/appium/lib directory did have a main.js file in it, but no directory named "server". So I created such a directory and placed a copy of the main.js file in that, but got more errors. And at that point decided that using the Appium Inspector from 1.4.13 simply ain't gonna work with headless Appium 1.5.2 at all, unless someone on the Dev team wants to give me pointers.

In the meantime, I will have to use the Android SDK itself to create my Android gui automation, and that will be a pain.
