### ISSUE TITLE
NoSuchSessionException exception is thrown while using java-client-5.0.0-BETA6.jar with appium 1.6.5 server 

### ISSUE THREAD

**Issue by SinghSomnath** [appium/appium#8625]
## The problem

java.lang.NoClassDefFoundError: org/openqa/selenium/NoSuchSessionException  is thrown while initiating the IOSDriver object using java-client-5.0.0-BETA6.jar with appium 1.6.5 server .

My DesiredCapabilities looks like

```
DesiredCapabilities capabilities = new DesiredCapabilities();
 capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.5");
 capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3");
 capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
 capabilities.setCapability(MobileCapabilityType.APP, "/Users/admin/someDir/sample.App");
```

**Below is the line which is throwing the error.**

`WebDriver driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): works fine with java-client-5.0.0-BETA5.jar but does not work with java-client-5.0.0-BETA6.jar onwards even ver 7,8 too fails .
* Desktop OS/version used to run Appium: Mac 10.12 (Sierra)
* Node.js version (unless using Appium.app|exe): 8.0.0
* Mobile platform/version under test: 10.3/iPhone 6
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: na

Advanced thanks for any input on this .

**Comment by mykola-mokhnach** [comment]
NoSuchSessionException is only present in Selenium 3+, so you need to check your maven/gradle config on whether you use correct version of selenium library together with java client.

Closing this issue as not Appium-related. Please report it to https://github.com/appium/java-client

**Comment by SinghSomnath** [comment]
I am using selenium-server-standalone-2.53.0.jar along with  java-client-5.0.0-BETA6.jar . Selenium 3+ jar is not used .

**Comment by mykola-mokhnach** [comment]
And this is the problem. java client 5 requires selenium 3.

**Comment by SinghSomnath** [comment]
yes, all solved . Thanks .
