### ISSUE TITLE
Encountered internal error running command: Error: targetSdkVersionFromManifest failed. Original error: Cannot read property '1' of null

### ISSUE THREAD

**Issue by jhwing** [appium/appium#7353]
when i run sample-code android_simple.py i got this error ,i search everywhere ,no result

[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/jihongwen/Development/android/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","760ABLMW96TX","shell","am","force-stop","io.appium.unlock"]
[debug] [Logcat] Stopping logcat capture
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: targetSdkVersionFromManifest failed. Original error: Cannot read property '1' of null
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (../../../lib/tools/android-manifest.js:101:9)
    at tryCatch (/Users/jihongwen/.nvm/versions/node/v7.2.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jihongwen/.nvm/versions/node/v7.2.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jihongwen/.nvm/versions/node/v7.2.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/jihongwen/.nvm/versions/node/v7.2.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 1585 ms

**Comment by joodies** [comment]
same issue here  withe appium 1.6.2

**Comment by sankleta** [comment]
#7349 The same here

**Comment by sravanmedarapu** [comment]
Seems something broken with appium-adb v2.9.0, Please downgrade appium-adb to v2.7.0 as a temporary work around.

**Comment by chanisasuw** [comment]
same me via window 7
I installed appium version 1.6.2

**Comment by sravanmedarapu** [comment]
@chanisasuw, I am working on this issue. As a temporary workaround, please downgrade appium-adb to 2.7.0.

npm install appium-adb@2.7.0

**Comment by mykola-mokhnach** [comment]
It is also possible to avoid the issue for now by explicitly setting the _android:targetSdkVersion_ property in the manifest file (https://developer.android.com/guide/topics/manifest/uses-sdk-element.html). It seems like the actual implementation does not respect the fact, that this property can be omitted (and it is equal to _android:minSdkVersion_ in such case). 

@jlipps FYI

**Comment by chanisasuw** [comment]
Thank you so much for working this issue, It didn't work for me.
For temporary I install Appium version 1.6.0 , it work fine

npm install appium@1.6.0

**Comment by joodies** [comment]
tried
   npm install  -g appium-adb@2.7.0

finally it's working now..

**Comment by oomkarpandit** [comment]
@mykola-mokhnach : What am I suppose to change in manifest file?

**Comment by jeangb** [comment]
Hi, this workaround "npm install appium-adb@2.7.0" didn't change a thing neither.

**Comment by devin-joubran-moovel** [comment]
Hi,

I'm also experiencing this issue on a mac 10.11.6, android nexus 5 api 23; appium 1.6.2. Tried appium-adb 2.7.0 and no changes

**Comment by Rdexmah** [comment]
Hey I am also facing same issue with ios10.0.1 and with latest appium 1.6.2 beta.. 
You got any resolution >

**Comment by cavanpage** [comment]
npm install appium-adb@2.7.0 worked for me. 

I am pretty new to node so I wasn't installing it into the right place at first. 
Make sure you execute that command within the appium directory (for windows the default location for me is C:\Users\myusername\AppData\Roaming\npm\node_modules\appium\" )

I am running appium@1.6.0 on windows 7, testing a Samsung S6 with the newest chrome app.

 I also had to replace the "appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe" with the latest driver from here https://sites.google.com/a/chromium.org/chromedriver/ . This stopped  the "NoSuchSession" error. 

My tests are running great now.

**Comment by lilfry14** [comment]
I was having this issue with appium 1.6 on a Mac 10.11.6 and npm install appium-adb@2.7.0 worked for me.

**Comment by viveksinghtt** [comment]
i have this issue as well...on mac...npm install -g appium-adb@2.7.0 didnt work.... @sravanmedarapu can you please provide a hotfix for this?

**Comment by jeangb** [comment]
Apart downgrading to appium-adb@2.7.0, if it doesn't work, is there an other workaround while waiting the hotfixe ?

**Comment by sravanmedarapu** [comment]
@jeangb, I am working on this issue. Will update here once issue is fixed.

**Comment by jeangb** [comment]
@sravanmedarapu, Thank you very much for your quick feedback.

**Comment by z00sts** [comment]
Same.
Downgrading to appium-adb@2.7.0 helps. 
Any ideas why appium-adb 2.8+ is not working with appium@1.6+?

**Comment by vikramvi** [comment]
+1

https://gist.github.com/vikramvi/2717dbd538e23515c406fd6b4703ed29

**Comment by vikramvi** [comment]
@jlipps can we please have a hot fix release for this

**Comment by saikrishna321** [comment]
@vikramvi this issue has been picked by @sravanmedarapu  and he is working on it ..

**Comment by vikramvi** [comment]
Workaround for now as below

Goto directory /usr/local/lib/node_modules/appium 
and run below command
npm install appium-adb@2.7.0

After this npm -g ls , shows updated appium-adb@2.7.0 from appium-adb@2.9.0

**Comment by steveyoungqa** [comment]
I can confirm that after struggling with this issue all weekend installing on the latest Macbook Pro that the above workaround works perfect!

**Comment by upadhyaynidhi** [comment]
@vikramvi 
Getting such errors after Goto directory /usr/local/lib/node_modules/appium
and run below command
npm install appium-adb@2.7.0

```
Error: Cannot find module 'babel-runtime/helpers/sliced-to-array'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/build/lib/main.js:7:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by chenyu22** [comment]
Same issue happened for me, I downgraded appium to 1.6.1 it works again. 
Have any one tried the 1.6.3 version of appium, just want to check if it is fixed or not

**Comment by sravanmedarapu** [comment]
@chenyu22 Issue is fixed in apapium-adb@2.9.1

**Comment by jibingli** [comment]
No compatible version found: appium@1.6.3, build failed?

**Comment by sravanmedarapu** [comment]
appium@1.6.3 is not released yet.

**Comment by cnpallares** [comment]
+1 @vikramvi  solution!

**Comment by davidrova** [comment]
I have the same issue with appium 1.6.2.

I have tried with appium-adb from 1.6.19 to latest with no sucess.

Any workaround? It is blocker.

Would the workaround be change manifest from android project? 

I have several manifest files with the targetSdkVersion parameter, so I don't know where appium-adb is looking for this parameter. Which file path is opening?

**Comment by sravanmedarapu** [comment]
@davidrova, Issue is fixed in appium-adb@v2.9.1.

**Comment by davidrova** [comment]
Hi @sravanmedarapu,

I have checked that version. The exception still is thrown but it is true the application starts.

I still don't know which AndroidManifest.xml is appium-adb looking for because in our proyect it exists. 

What we have checked is that in the apk it is cypher, but adb should decode it, isn't it?

If you need more info, let me know.

Regards,

PD. For the stakeholders: remember to restart appium after upgrade appium-adb.

**Comment by sravanmedarapu** [comment]
@davidrova, This implementation is as part of granting permissions to the AUT. but for granting the permissions we are relaying on device API (API >= 23) and `targetSdkVersion` from the AUT (targetSdkVersion >= 23). 

We are relying on [`aapt dump badging APK`](https://github.com/appium/appium-adb/blob/478d97e65658d10fa920bc786447b985de83a29f/lib/tools/android-manifest.js#L96) command's result for fetching the `targetSdkVersion`. if the `targetSdkVersion`  < 23, we are just skipping the permissions granting. 

But there are cases where we don't find `targetSdkVersion` in the dump result and  in such case we are throwing the [exception](https://github.com/appium/appium-adb/blob/478d97e65658d10fa920bc786447b985de83a29f/lib/tools/android-manifest.js#L100) and ignoring the execution to continue with.

**Comment by vincentlabatut** [comment]
Hi, 
using 1.6.2 on windows. Just upgraded appium-adb to 2.9.1 but I still have the error.
`Encountered internal error running command: Error: targetSdkVersionFromManifest failed. Original error: Cannot read property '1' of null`
And I get an internal error (http 500) so my test is failing, appium stops processing.
Just checked adb version : Android Debug Bridge version 1.0.36
Revision 302830efc153-android
This is blocking me :(

**Comment by sravanmedarapu** [comment]
@vincentlabatut, seems updating appium-adb to 2.9.1 was not successful. Can you please cross check(version in appium\node-modules\appium-adb\package.json).

Just to conform error message you have shared is related to 2.9.0, error [message](https://github.com/appium/appium-adb/blob/478d97e65658d10fa920bc786447b985de83a29f/lib/tools/android-manifest.js#L100) is changed in 2.9.1. 

execute `npm install appium-adb@2.9.1` from appium repo.

**Comment by nrazvan87** [comment]
I've tried all solutions presented above but didn't work for me :(
I've installed then `npm install appium-adb@1.6.0` and everything started to work smoothly.

Thanks for the tips, It was a good starting point!

**Comment by vincentlabatut** [comment]
Thanks ! Just did that : workaround for 1.6.2 is reverting to 1.6.0
it works again :)

**Comment by sravanmedarapu** [comment]
Issue is fixed in appium-adb v2.9.1

**Comment by vincentlabatut** [comment]
Hi, I was just saying that I installed appium-adb to 2.9.1 and the issue was still there...

**Comment by jeangb** [comment]
Yes me to, I guess the appium-adb 2.9.1 install didn't work.

**Comment by vincentlabatut** [comment]
Got it! My fault. I did not install appium-adb correctly because we need to upgrade the appium-adb module that is inside the node_modules of the node_modules/appium folder.
so just saying npm install appium-adb@2.9.1 is not sufficient. You have to do that from the node_modules\appium folder in order to upgrade the appium-adb that is where appium will find it.
We are not all nodejs expert (at least I am not), but now it looks obvious to me.

Result is that it is working :)

The error is displayed
[ADB] Error: fetching targetSdkVersion from local APK failed. Original error: targetSdkVersion is not specified in the application.
(with the full stack trace)
[ADB] Ran into problem getting target SDK version; ignoring...

And all is working...

**Comment by z00sts** [comment]
@vincentlabatut Yep, nodejs local installation always confusing. @jeangb check that you upgrading appium-adb in your appium/node_modules

**Comment by jeangb** [comment]
Yes it was because I was doing "npm install appium-adb@2.9.1" from $home...
I thought it will be installed in the right folder since the first time I installed appium with npm, it was installed in a custom folder and not in $home.
So yes, it's working with appium-adb 2.9.1, thanks.

**Comment by srkannan** [comment]
I did npm install -g appium-adb@2.9.1 in /usr/local/lib/node_modules/appium
But I still have the issue. I'm using Appium version 1.6.2

**Comment by SteffenL** [comment]
I updated appium-adb to v2.9.1, but the issue persists in my case.

Environment:
- macOS 10.12
- Node.js 7.1.0
- Appium 1.6.2
- Selenium 3.0.1
- Android 5.1 / API level 22

Update appium-adb and verify:
```
$ which appium
/usr/local/bin/appium
$ readlink `which appium`
../lib/node_modules/appium/build/lib/main.js
$ cd /usr/local/lib/node_modules/appium
$ npm install appium-adb@2.9.1
$ npm list -g appium-adb
/usr/local/lib
└─┬ appium@1.6.2
  └─┬ appium-android-driver@1.10.36
    └── appium-adb@2.9.1
```

Python script for testing:
```
from selenium import webdriver

cap = {"browserName": "Browser", "platformName": "Android", "deviceName": "Android Emulator", "platformVersion": "5.1", "automationName": "Appium", "avd": "Nexus_5"}
driver = webdriver.Remote("http://localhost:4723/wd/hub", cap)
driver.get("http://www.seleniumhq.org/")
driver.quit()
```

**Comment by saikrishna321** [comment]
@srkannan please upgrade appium version to 1.6.3 , thats got the fix

**Comment by srkannan** [comment]
Upgrading to appium version 1.6.3 helped, Thanks.

**Comment by Hiran47** [comment]
> Goto directory /usr/local/lib/node_modules/appium
> and run below command
> npm install appium-adb@2.7.0

This has worked for me as well.
OS X 10.12.3
Appium 1.6.2
