### ISSUE TITLE
Select Not Working in Android Webview in Appium 1.9.1 (CLI)

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium#11416]
## The problem
I have a Hybrid app and when trying to select dropdown in a webview, appium server throws error. It works fine in 1.8.0(Appium desktop) but in 1.9.1(Appium CLI) its not working.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: Windows 10 and Linux
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Nexus 6 With Android 6.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
https://gist.github.com/MummanaSubramanya/a9da59af5ed54e5372f7f760ebbc8fd6

## Code To Reproduce Issue [ Good To Have ]
var selectElement = new SelectElement(AppElement);
selectElement.SelectByText(value);
return true;

**Comment by mykola-mokhnach** [comment]
I would say this problem has more to do with selenium/chromedriver rather than with appium

**Comment by MummanaSubramanya** [comment]
@mykola-mokhnach Thanks for replying. With appium 1.8.1 I had chromedriver v38 which works absolutely fine. Since Select was not working with appium 1.9.1 I replaced the chromedriver v42 with chromedriver v38 and still the scripts fails. Do you still think its chromedriver issue? Could you please check the gist which I have posted?

**Comment by MummanaSubramanya** [comment]
@mykola-mokhnach this is the exception which Im getting:

 System.InvalidOperationException: An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function

**Comment by MummanaSubramanya** [comment]
@mykola-mokhnach any update on it ?

**Comment by acopapic** [comment]
Is this solved? I have the same problem with Appium 1.10.0 and chromedrivers v44 and v45. I'm using .net Selenium client and during instantiation of the Select element I get:

An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function
