### ISSUE TITLE
node-gyp error when upgrading to v1.8.1

### ISSUE THREAD

**Issue by damitas** [appium/appium#11082]
## The problem

Trying to upgrade to appium 1.8.1 I get the following error:

```
Output:
module.js:538
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
```

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: MacOS 10.13.2
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test: IOS
* Yarn: v1.3.2

## Details

Simply running: 'Yarn' at command prompt and the error occurs

I understand in the past you have mentioned Appium does not support Yarn, is this still the case? when Yarn receives over 300,000 downloads per week?

## Link to Appium logs

```
error  /node_modules/buffertools: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory:  /node_modules/buffertools
Output:
module.js:538
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
```

## Code To Reproduce Issue [ Good To Have ]

package.json includes this extract:

```
"devDependencies": {
"appium": "^1.8.1",
}
```
At command prompt type:

`Yarn`

**Comment by mykola-mokhnach** [comment]
Yes, we neither test not support yarn, but only npm. Use it at your own risk. Closed as not an issue.

**Comment by imurchie** [comment]
Seems like you don't have `node-gyp` installed. Yarn ought to handle it (https://github.com/yarnpkg/yarn/issues/3114) but you could try installing it globally, or add it to your project. Not sure how to do that with Yarn, though.
