### ISSUE TITLE
AppiumDriver is not working with java-client-3.2.0 jar

### ISSUE THREAD

**Issue by jaipaddy** [appium/appium#5857]
Here is my pom.xml
```<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>3.2.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.seleniumhq.selenium</groupId>
					<artifactId>selenium-java</artifactId>
				</exclusion>
			</exclusions>
		</dependency>```

In Eclipse, I see a compilation error on AndroidDriver/AppiumDriver. I have tried 

wd = new AppiumDriver(url , capabilities);
wd = new AndroidDriver(url , capabilities);
wd = new AndroidDriver<MobileElement>(url , capabilities);

I can see the jar in my classpath and under .m2.

Unresolved compilation problem: 
	The type org.openqa.selenium.remote.service.DriverService$Builder cannot be resolved. It is indirectly referenced from required .class files

This is a blocker

**Comment by jaipaddy** [comment]
The error was resolved by adding selenium-remote-driver to the pom followed by mvn eclipse:eclipse. This should be documented clearly
