### ISSUE TITLE
Appium 4.1.x and 5.0.0 BETAX PageFactory throws NoSuchMethodError on FluentWait.util when using Selenium 3.1.0 and 3.2.0

### ISSUE THREAD

**Issue by tony221** [appium/appium#7970]
## The problem

May be an issue with Selenium new releases, but posting here for people who may find same issue

Using PageFactory throws NoSuchMethodError on Selenium FluentWait.util on Selenium 3.1.x - 3.2, it works with Selenium 3.0.1 successfully

## Environment

* Appium version (or git revision) that exhibits the issue: 4.1.X - 5.0.0 BETAX
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:OSX 10.12.2
* Node.js version (unless using Appium.app|exe): 7.6.0
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/tony221/eaf47cefe1edcb38a7ebdf98fadbe5b8

## Code To Reproduce Issue [ Good To Have ]

public class HomePageAndroid extends BasePage<HomePageAndroid> {

    @AndroidFindBy(id = CLICK_AND_COLLECT_ID)
    private AndroidElement clickAndCollectOption;

     .....

   @Inject
    public HomePageAndroid(AppiumDriver driver) {
        super(driver);
// initialised in super with - *PageFactory.initElements(new AppiumFieldDecorator(driver), this)* 
    }

   public void clickOnClickAndCollect() {
// below line works
//        waitForVisibilityOfElement(By.id(CLICK_AND_COLLECT_ID),30).click();

//TODO: not working with lazy initialisation when using PageFactory, throws NoSuchMethodException
        waitForVisibilityOfElement(By.id(CLICK_AND_COLLECT_ID),30);
        clickAndCollectOption.click();
    }
     ......
}

**Comment by jrscanlon** [comment]
This is really an issue with the java-client. Selenium 3.1.0 switched from using com.google.common.base.Function to java.util.function.Function in FluentWait.until( ).

From https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG

v3.1.0
=====

* Update Wait and FluentWait for Java 8. Requires an update to the
  latest guava version 21.0

v3.2.0
======

* Remove deprecated `FluentWait.until(Predicate<?>)` method. This
  should make lambdas work properly with Wait instances now.

In java-client:
src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java
src/test/java/io/appium/java_client/android/AndroidFunctionTest.java

Need to change references to com.google.base.Function to java.util.function.Function.

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey @saikrishna321 FYI

**Comment by SrinivasanTarget** [comment]
cool @mykola-mokhnach @tony221 Will look into this

**Comment by SrinivasanTarget** [comment]
@jrscanlon Would you like to raise a PR? Happy to review :)

**Comment by TikhomirovSergey** [comment]
Guys. It is not related to appium backend. Please close it

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey sure. We just wanted you know about the problem.

**Comment by tony221** [comment]
@TikhomirovSergey would you mind giving your opinion of possible cause of this issue?
