### ISSUE TITLE
UiAutomator2 xpath NoClassDefFoundError when using xpath substring

### ISSUE THREAD

**Issue by Auto81** [appium/appium#16337]
## The problem

Element failing to be found via the below xpath with a NoClassDefFoundError

```
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Located by By.chained({By.xpath: //android.view.ViewGroup[substring(@resource-id, string-length(@resource-id) - string-length('toolbar') + 1)  = 'toolbar']//android.widget.TextView})

Caused by: org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ibm/icu/text/UTF16;
```

```[WD Proxy] Got response with status 500: {"sessionId":"272c597a-3614-49a5-9f37-0ca2eadc9b1c","value":{"error":"unknown error","message":"java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ibm/icu/text/UTF16;","stacktrace":"java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ibm/icu/text/UTF16;\n\tat org.eclipse.wst.xml.xpath2.processor.internal.function.FnStringLength.string_length(FnStringLength.java:105)\n\tat org.eclipse.wst.xml.xpath2.processor.internal.function.FnStringLength.evaluate(FnStringLength.java:75)\n\tat org.eclipse.wst.xml.xpath2.processor.DefaultEvaluator.visit(DefaultEvaluator.java:1593)\n\tat org.eclipse.wst.xml.xpath2.processor.internal.ast.FunctionCall.accept(FunctionCall.java:57)\n\tat org.eclipse.wst.xml.xpath2.processor.DefaultEvaluator.visit(DefaultEvaluator.java:2110)\n\tat org.eclipse.wst.xml.xpath2.processor.internal.ast.FilterExpr.accept(FilterExpr.java:53)\n\tat org.eclipse.wst.xml.xpath2.processor.DefaultEvaluator.visit(DefaultEvaluator.java:1275)\n\tat org.eclipse.wst.xml.xpath2.processor.internal.as...```

This also happens through Inspector

![Screenshot 2022-01-14 at 10 12 23](https://user-images.githubusercontent.com/48491431/149498661-3b982535-7f82-4d68-a696-eed919ef290b.png)

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 2 with UiAutomator2@1.75.0
* Last Appium version that did not exhibit the issue (if applicable): Appium 2 with UiAutomator2@1.73.0
* Desktop OS/version used to run Appium: Mac Big Sure M1 Mac Mini
* Node.js version (unless using Appium.app|exe): 14.15.4
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator 
* Appium CLI or Appium.app|exe: CLI

## Details

UiAutomator2 driver was working with v1.73.0.
Upgraded to v1.75.0, began failing.
Uninstalled 'Appium Settings', 'io.appium.uiautomator2.server', 'io.appium.uiautomator2.server.test' from emulator.
Downgraded to v1.73.0.
Error still happening.

Same tests work when running through appium CLI v1.22.0

Taking the page source and running on an external evaluator also works.

**Comment by mykola-mokhnach** [comment]
Please try with the server apk built from the branch from https://github.com/appium/appium-uiautomator2-server/pull/453

**Comment by Auto81** [comment]
Cant understand the readme on https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli

What is wrong with the following?

`appium driver install --source=github --package=appium-uiautomator2-server mykola-mokhnach/appium-uiautomator2-server/tree/icu`

**Comment by mykola-mokhnach** [comment]
appium-uiautomator2-server is not a driver, so it won't work this way. It is necessary to build and deploy the server package manually manually to the device under test in order to check the fix

**Comment by Auto81** [comment]
Built via gradle and installed onto device

Via inspector xpath search
`//*[substring(@text, 1) = 'SIGN IN']`

now provides a different error
`Call to 10 failed
An unknown server-side error occurred while processing the command. Original error: java.lang.NoSuchMethodError: No static method isHighSurrogate(C)Z in class Lcom/ibm/icu/lang/UCharacter; or its super classes (declaration of 'com.ibm.icu.lang.UCharacter' appears in /data/app/~~avVSAn-YcXTn9077VB4GqA==/io.appium.uiautomator2.server-lg2OpInthHjS8MHcoR_VbA==/base.apk)
`

//*[@text = 'SIGN IN'] works and finds element

**Comment by mykola-mokhnach** [comment]
I have updated the branch and it should be fine now. Looks like an older version of ICU was needed

**Comment by Auto81** [comment]
Looks to be working for me too

**Comment by mykola-mokhnach** [comment]
Cool, the patch has been published
