### ISSUE TITLE
Exception "onUnexpectedShutdown is not a function" while connecting to Chrome on Appium 1.16.0-rc.0

### ISSUE THREAD

**Issue by alcoredev** [appium/appium#13672]
## The problem

Appium 1.16.0-rc.0 fails to open Chrome session on real Android device with error 
TypeError: driver.onUnexpectedShutdown is not a function

## Environment

* Appium: v1.16.0-rc.0
* Desktop OS: Windows 10
* Node.js: v10.15.3
* Npm: v6.4.1
* Mobile platform: Android 9
* Real device: Samsung S8
* Appium CLI or Appium.app|exe: CLI

## Details

Appium was installed using NPM: 
`npm install appium@1.16.0-rc.0 --prefix d:/bin/agent/appium`

See more details in logs.
Note: the same configuration works with Appium 1.16.0-beta.3

## Link to Appium logs

https://gist.github.com/alcoredev/d6028f1df887452f91c2f571efcab32b

## Code To Reproduce Issue [ Good To Have ]

Java:
`

        Map<String, String> env = new HashMap<>();
        env.put("ANDROID_HOME", "d:\\bin\\android-sdk");

        AppiumServiceBuilder builder = new AppiumServiceBuilder();
        builder.usingAnyFreePort()
                .usingDriverExecutable(new File("d:\\bin\\agent\\nodejs\\node.exe"))
                .withAppiumJS(new File("d:\\bin\\agent\\appium\\node_modules\\appium"))
                .withEnvironment(env);

        AppiumDriverLocalService server = builder.build();
        server.start();

        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setBrowserName("Chrome");
        caps.setPlatform(Platform.ANDROID);
        caps.setCapability(MobileCapabilityType.UDID, "ce01182113382b2401");
        caps.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 0);
        caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
        caps.setCapability(AndroidMobileCapabilityType.CHROMEDRIVER_EXECUTABLE,
                "d:\\bin\\agent\\webdrivers\\mobile\\drivers\\win\\chromedriver_win32_78.0.3904.70.exe");

        RemoteWebDriver driver = new RemoteWebDriver(server.getUrl(), caps);
        driver.get("http://google.com");
        driver.quit();

        server.stop();
`

**Comment by mykola-mokhnach** [comment]
duplicate of https://github.com/appium/appium/issues/13660
